
# Site settings
title: Zejin Shi
name: Zejin Shi
subtitle:  PhD Candidate in Economics
email: zejinshi@arizona.edu
description: >
   PhD in Economics
baseurl: ""
url: "https://shizejin.github.io/"
github_username:  shizejin
disqus_baseurl: "https://shizejin.github.io/"
disqus_shortname: https-shizejin-github-io
permalink: :title

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"
inter_post_navigation: true

defaults:
  -
    scope:
      path: ""
    values:
      author: "Zejin Shi"



# External gems
gems:
  - jekyll-paginate
  - jemoji
  - jekyll-seo-tag



social:
  - name: GitHub
    icon: github
    username: zejinshi
    url: https://github.com/shizejin
    desc: Fork me on GitHub
    share: false

  - name: LinkedIn
    icon: linkedin
    username: Zejin Shi
    url: https://www.linkedin.com/in/zejinshi/
    desc: Connect with me on LinkedIn
    share: true
